---
- name: Install dnf-automatic.
  dnf:
    name: dnf-automatic
    state: present

- name: Configure dnf-automatic.
  template:
    src: dnf-automatic.conf.j2
    dest: /etc/dnf/automatic.conf
    owner: root
    group: root
    mode: 0644

- name: Enable dnf-automatic.
  service:
    name: dnf-automatic.timer
    enabled: yes